### ISSUE TITLE
Derivative work from record project

### ISSUE THREAD

**Issue by llfbandit** [josephcrowell/flutter_record#1]
I saw your project published on pub.dev.
Regarding the modifications applied to the repository, you are not compliant with the Apache 2.0 license as you are not stating the changes made to the original content.

Regarless the above, this is a waste to not contribute to the record package to make a duplicate of it...

**Comment by josephcrowell** [comment]
Feel free to pull any changes from the clearly visible and detailed commit history which shows the changes that were made. The original project I forked this from had a large disclaimer that they were discontinuing the project and to use flutter_sound instead. The one I forked was broken and in need of repair and hadn't seen development in over a year. This was easier than starting from scratch since I would have basically written the same thing since it's just a loose wrapper around existing APIs.

**Comment by llfbandit** [comment]
I'm the maintainer of this project so I know pretty well where my time is spent. 
Anyway, I got my answers in between what you said and what you did.
